#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/_build/html"

if [[ ! -d .git ]]; then
    git init .
fi

touch .nojekyll

git add .
git commit -m "$(date)"

git push -f git@github.com:mikeboers/dbapix.git HEAD:gh-pages

